[package]
name = "procedural-engines-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.28"

# bin
boids-engine = { path = "../engines/boids-engine" }
topography-engine = { path = "../engines/topography-engine" }
