[package]
name = "topography-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
js-sys = "0.3"
rand = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }